<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SubjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
{
 $data = [
 ['subj_no'=>'BM 101', 'subj_name'=>'Essentials of Business and Management'],
 ['subj_no'=>'BM CORE 2', 'subj_name'=>'Strategic Management'],
 ['subj_no'=>'ENT 101', 'subj_name'=>'Social Entrepreneurship'],
 ['subj_no'=>'ENT B', 'subj_name'=>'Entrepreneurial Behavior'],
 ['subj_no'=>'ENT F', 'subj_name'=>'Costing & Pricing'],
 ['subj_no'=>'ENT G', 'subj_name'=>'Market Research & Consumer Behavior'],
 ['subj_no'=>'ENT H', 'subj_name'=>'Business Plan Preparation'],
 ['subj_no'=>'ENT J', 'subj_name'=>'Business Plan Implementation B'],
 ['subj_no'=>'ENT K', 'subj_name'=>'Programs & Policies on Enterprises Development'],
 ['subj_no'=>'ENT L', 'subj_name'=>'Financial Management'],
 ['subj_no'=>'ENT ELEC 4', 'subj_name'=>'Microfinancing'],
 ['subj_no'=>'OM 3', 'subj_name'=>'Project Management'],
 ['subj_no'=>'OM 4', 'subj_name'=>'Inventory Management and Control'],
 ['subj_no'=>'OM 5', 'subj_name'=>'Costing & Pricing'],
 ['subj_no'=>'OM 11', 'subj_name'=>'Facilities Management'],
 ['subj_no'=>'OM 10', 'subj_name'=>'Business Research 2'],
 ['subj_no'=>'OM ELEC 4', 'subj_name'=>'Special Topics in Operations Management II'],
 ['subj_no'=>'OM ELEC 2', 'subj_name'=>'Management Information System/OM Elective (lec/lab)'],
 ['subj_no'=>'OM ELEC 3', 'subj_name'=>'Enterprise Resource Planning/OM Elective (Lec/Lab)'],
 ['subj_no'=>'ACCTG 102', 'subj_name'=>'Intermediate Accounting 1'],
 ['subj_no'=>'Tax 1', 'subj_name'=>'Income Taxation'],
 ['subj_no'=>'Tax 3', 'subj_name'=>'Other Taxes and Preferential Taxation'],
 ['subj_no'=>'ACCTG 403', 'subj_name'=>'Auditing and Assurance: Concepts and Applications 1'],
 ['subj_no'=>'ACCTG 206', 'subj_name'=>'Financial Management'],
 ['subj_no'=>'ACCTG 502', 'subj_name'=>'Accounting Research'],
 ['subj_no'=>'ACCTG 301', 'subj_name'=>'Accounting for Special Transactions'],
 ['subj_no'=>'ACCTG 101', 'subj_name'=>'Financial Accounting and Reporting'],
 ['subj_no'=>'Tax B', 'subj_name'=>'Business and Transfer Taxation'],
 ['subj_no'=>'ACCTG 202', 'subj_name'=>'Strategic Business Analysis'],
 ['subj_no'=>'ACCTG 105', 'subj_name'=>'Intermediate Accounting 4'],
 ['subj_no'=>'ACCTG 406', 'subj_name'=>'Auditing in CIS Environment (Lec/Lab)'],
 ['subj_no'=>'ACCTG 702', 'subj_name'=>'Performance Management Systems'],
 ['subj_no'=>'ACCTG 302', 'subj_name'=>'Accounting for Government and Non-Profit Organizations'],
 ['subj_no'=>'ACCTG 401', 'subj_name'=>'Governance Business Ethics Risk Management and Internal Control'],
 ['subj_no'=>'RFBT 4', 'subj_name'=>'Law on Banking and Other Laws'],
 ['subj_no'=>'RFBT 2', 'subj_name'=>'Law on Business Associations'],
 ['subj_no'=>'ACCTG 407', 'subj_name'=>'Auditing and Assurance: Specialized Industries'],
 ['subj_no'=>'LAW A', 'subj_name'=>'Law on Obligations & Contracts'],
 ['subj_no'=>'LAW B', 'subj_name'=>'Law on Banking and Other Laws'],
 ['subj_no'=>'FM 8B', 'subj_name'=>'Investment and Portfolio Management Part 11'],
 ['subj_no'=>'MGT 202', 'subj_name'=>'Management Science'],
 ['subj_no'=>'FM 17', 'subj_name'=>'Business Research II'],
 ['subj_no'=>'FIN 101', 'subj_name'=>'Principles of Finance'],
 ['subj_no'=>'FM 7', 'subj_name'=>'Capital Market and Financial Market'],
 ['subj_no'=>'FM 9', 'subj_name'=>'Credit and Collection'],
 ['subj_no'=>'FM 2', 'subj_name'=>'Banking and Financial Institutions'],
 ['subj_no'=>'FM 14', 'subj_name'=>'Special Topics in Financial Management'],
 ['subj_no'=>'FM 13', 'subj_name'=>'Behavioral Finance'],
 ['subj_no'=>'ENT ELEC 1', 'subj_name'=>'Technopreneurship/Elective'],
 ['subj_no'=>'MKTG 101', 'subj_name'=>'Principles of Marketing'],
 ['subj_no'=>'MM 1', 'subj_name'=>'Product Management'],
 ['subj_no'=>'MM 5', 'subj_name'=>'Advertising and Sales Promotion'],
 ['subj_no'=>'MM 6', 'subj_name'=>'Professional Salesmanship'],
 ['subj_no'=>'MM 9', 'subj_name'=>'Marketing Research Paper II'],
 ['subj_no'=>'MM 10', 'subj_name'=>'Marketing Management/Marketing Elective'],
 ['subj_no'=>'MM 11', 'subj_name'=>'Internship (600 hours)'],
 ['subj_no'=>'MM ELEC 1', 'subj_name'=>'Consumer Behavior/Marketing Elective'],
 ['subj_no'=>'MM ELEC 3', 'subj_name'=>'E-Commerce & Internet Marketing/Marketing Elective (Lec/Lab)'],
 ['subj_no'=>'MM ELEC 4', 'subj_name'=>'Special Topics in Marketing/Marketing Elective'],
 ['subj_no'=>'MM ELEC 5', 'subj_name'=>'Service Marketing/Marketing Elective'],
 ['subj_no'=>'HRM 1', 'subj_name'=>'Human Resource Management'],
 ['subj_no'=>'HRM 5', 'subj_name'=>'Organizational Development'],
 ['subj_no'=>'HRM 6', 'subj_name'=>'Administrative and Office Management'],
 ['subj_no'=>'HRM 9', 'subj_name'=>'Business Research 11'],
 ['subj_no'=>'HRM 10', 'subj_name'=>'Special Topics in Human Resource Management'],
 ['subj_no'=>'HRM 11', 'subj_name'=>'Labor Relations'],
 ['subj_no'=>'HRM 12', 'subj_name'=>'Internship (600 hours)'],
 ['subj_no'=>'HRM Elec 1', 'subj_name'=>'Logistics Management /HRM Elective'],
 ['subj_no'=>'HRM Elec 2', 'subj_name'=>'Occupational Safety and Health/HRM Elective'],
 ['subj_no'=>'HM 5', 'subj_name'=>'Food and Beverage Cost Control'],
 ['subj_no'=>'HM 6', 'subj_name'=>'Kitchen Essentials and Basic Food Preparation'],
 ['subj_no'=>'HM 7', 'subj_name'=>'Fundamentals in Food Service Operations'],
 ['subj_no'=>'HM 8', 'subj_name'=>'Philippine Culture and Tourism Geography'],
 ['subj_no'=>'Sanitation', 'subj_name'=>'Risk Management as Applied to Safety Security and Sanitation'],
 ['subj_no'=>'HM 14', 'subj_name'=>'Operations Management'],
 ['subj_no'=>'HM 15', 'subj_name'=>'Multicultural Diversity in the Workplace for Tourism Professional'],
 ['subj_no'=>'HM 16', 'subj_name'=>'Entrepreneurship in Tourism and Hospitality Industry'],
 ['subj_no'=>'HM 17', 'subj_name'=>'Professional Development and Applied Ethics'],
 ['subj_no'=>'HM 24', 'subj_name'=>'Research in Hospitality 2'],
 ['subj_no'=>'HM 25', 'subj_name'=>'Rooms Division Cost Control'],
 ['subj_no'=>'HM 26', 'subj_name'=>'Tourism and Hospitality Marketing'],
 ['subj_no'=>'HM F&B 23', 'subj_name'=>'Research 2'],
 ['subj_no'=>'HM F&B 24', 'subj_name'=>'Tourism and Hospitality Marketing'],
 ['subj_no'=>'CULINARY 3', 'subj_name'=>'Bread and Pastry'],
 ['subj_no'=>'CULINARY 4', 'subj_name'=>'Classic French Cuisine'],
 ['subj_no'=>'Practicum 2', 'subj_name'=>'Hotel Phase'],
 ['subj_no'=>'TM 3', 'subj_name'=>'Transportation Management'],
 ['subj_no'=>'TM 4', 'subj_name'=>'Ecotourism Management'],
 ['subj_no'=>'TM 5', 'subj_name'=>'Specialized Food and Beverage Operations'],
 ['subj_no'=>'TM 6', 'subj_name'=>'Philippine Culture and Tourism Geography'],
 ['subj_no'=>'Seminar', 'subj_name'=>'Tourism Seminar'],
 ['subj_no'=>'TM 14', 'subj_name'=>'Tourism and Hospitality Management Business Marketing Principles'],
 ['subj_no'=>'TM 15', 'subj_name'=>'Advanced Tour Guiding'],
 ['subj_no'=>'TM 16', 'subj_name'=>'Corporate Travel Management'],
 ['subj_no'=>'TM 17', 'subj_name'=>'Accommodations Operations and Management'],
 ['subj_no'=>'TM 23', 'subj_name'=>'Quality Service Management in Tourism and Hospitality'],
 ['subj_no'=>'TM 24', 'subj_name'=>'Research in Tourism 2'],
 ['subj_no'=>'TM 25', 'subj_name'=>'Leisure and Attractions Management'],
 ['subj_no'=>'Prac 2', 'subj_name'=>'Travel Industry Practice'],
 ['subj_no'=>'ENT A', 'subj_name'=>'The Entrepreneurial Mind'],
 ['subj_no'=>'Track 2', 'subj_name'=>'Meetings Incentives Conferences and Events Management'],
 ['subj_no'=>'Track 4', 'subj_name'=>'Meat Processing /Food Preservation (Lec/Lab)'],
 ['subj_no'=>'OM 14', 'subj_name'=>'Internship (600 hours)'],
 ['subj_no'=>'Tax A', 'subj_name'=>'Income Taxation'],
 ['subj_no'=>'Hos Acctg.', 'subj_name'=>'Accounting for Tourism ad Hospitality Industry'],
 ['subj_no'=>'Finance 1', 'subj_name'=>'Business Finance'],
 ['subj_no'=>'ACCTG 503', 'subj_name'=>'Accounting Internship'],
 ['subj_no'=>'ACCTG 603', 'subj_name'=>'Management Accounting Internship (600 Hours)'],
 ['subj_no'=>'OM 6', 'subj_name'=>'International Business and Trade'],
 ['subj_no'=>'OM ELEC 1', 'subj_name'=>'Systems Application Program (SAP) - (lec/lab)'],
 ['subj_no'=>'TM 27', 'subj_name'=>'Tourism and Hospitality Strategic Management and Total Quality Management'],
 ['subj_no'=>'TM 28', 'subj_name'=>'Legal Aspects in Tourism and Hospitality Management'],
 ['subj_no'=>'CULINARY 5', 'subj_name'=>'International Cuisine'],
 ['subj_no'=>'OM ELEC 5', 'subj_name'=>'Supply Chain Management'],
 ['subj_no'=>'FM 15', 'subj_name'=>'Risk Management'],
 ['subj_no'=>'BA 17', 'subj_name'=>'Business Plan Implementation ll'],
 ['subj_no'=>'EM 1A1', 'subj_name'=>'Engineering Calculus 1'],
 ['subj_no'=>'EM 1B1', 'subj_name'=>'Engineering Calculus 2'],
 ['subj_no'=>'EM 2B1', 'subj_name'=>'Advanced Mathematics'],
 ['subj_no'=>'NS 1B1', 'subj_name'=>'Physics for Engineers (Lec)'],
 ['subj_no'=>'NS 1B2', 'subj_name'=>'Physics for Engineers (Lab)'],
 ['subj_no'=>'ENHC 1', 'subj_name'=>'Enhanced Course'],
 ['subj_no'=>'IE 1B1', 'subj_name'=>'Basic Industrial Economics'],
 ['subj_no'=>'EDA 1', 'subj_name'=>'Engineering Data Analysis'],
 ['subj_no'=>'ES 14', 'subj_name'=>'Environmental Science and Engineering'],
 ['subj_no'=>'ES 6', 'subj_name'=>'Engineering Economics'],
 ['subj_no'=>'IE 2B1', 'subj_name'=>'Methods Engineering'],
 ['subj_no'=>'IE 2B2', 'subj_name'=>'Industrial Accounting 3'],
 ['subj_no'=>'IE Elective 1', 'subj_name'=>'Systems Dynamics'],
 ['subj_no'=>'ES 13', 'subj_name'=>'Office Productivity Tools'],
 ['subj_no'=>'IE 3B1', 'subj_name'=>'Project Feasibility'],
 ['subj_no'=>'IE 3B2', 'subj_name'=>'Ergonomics 2'],
 ['subj_no'=>'IE 3B3', 'subj_name'=>'Operations Management 2'],
 ['subj_no'=>'IE 3B4', 'subj_name'=>'Operations Research 3'],
 ['subj_no'=>'IE Elective 3', 'subj_name'=>'Special Topics in IE 1'],
 ['subj_no'=>'IE 4B1', 'subj_name'=>'IE Capstone Project 2'],
 ['subj_no'=>'IE 4B2', 'subj_name'=>'Quality Management Systems'],
 ['subj_no'=>'IE 4B3', 'subj_name'=>'Engineering Laws. Ethics and Standards'],
 ['subj_no'=>'IE Elective 5', 'subj_name'=>'Special Topics in IE 2'],
 ['subj_no'=>'ES 12', 'subj_name'=>'Technopreneurship 101'],
 ['subj_no'=>'ES 7', 'subj_name'=>'Engineering Management'],
 ['subj_no'=>'CPE 1B1', 'subj_name'=>'Programming Logic and Design'],
 ['subj_no'=>'CPE 2B1', 'subj_name'=>'Advanced Engineering Mathematics for Computer Engineering'],
 ['subj_no'=>'CPE 2B3', 'subj_name'=>'Data Structures and Algorithms'],
 ['subj_no'=>'CPE 3B1', 'subj_name'=>'Basic Occupational Health and Safety'],
 ['subj_no'=>'CPE 3B2', 'subj_name'=>'Project Management for Computer Engineers'],
 ['subj_no'=>'CPE 3B3', 'subj_name'=>'Microprocessors (Lec)'],
 ['subj_no'=>'CPE 3B4', 'subj_name'=>'Micrprocessors (Lab)'],
 ['subj_no'=>'CPE 3B5', 'subj_name'=>'Methods of Research'],
 ['subj_no'=>'CPE 3B7', 'subj_name'=>'CpE Laws and Professional Practice'],
 ['subj_no'=>'CPE SD2', 'subj_name'=>'Elective-Software Development 2'],
 ['subj_no'=>'CPE SD3', 'subj_name'=>'Elective-Software Development 3'],
 ['subj_no'=>'CPE 4B3', 'subj_name'=>'CpE on the Job Training (240 Hours Minimum)'],
 ['subj_no'=>'CPE 4B4', 'subj_name'=>'Seminars and Field Trips'],
 ['subj_no'=>'CPE 521', 'subj_name'=>'Computer Systems Architecture'],
 ['subj_no'=>'CPE 4B1', 'subj_name'=>'CpE Practice and Design 2'],
 ['subj_no'=>'ES 9', 'subj_name'=>'Computer Fundamentals and Programming'],
 ['subj_no'=>'GE EPM', 'subj_name'=>'Eastern Philosophy'],
 ['subj_no'=>'ME 4B1', 'subj_name'=>'Industrial Plant Engineering'],
 ['subj_no'=>'ME 4B2', 'subj_name'=>'Power Plant Design with Renewable Energy'],
 ['subj_no'=>'ME 4B3', 'subj_name'=>'ME Laws Ethics Contacts Codes & Standards'],
 ['subj_no'=>'ME 4B4', 'subj_name'=>'Mechanical Engineering Lab 3'],
 ['subj_no'=>'ME EL1C', 'subj_name'=>'Special Problems 2 (Lec)'],
 ['subj_no'=>'ME EL4B', 'subj_name'=>'Computer-Aided Design & Manufacturing (Lec/Lab)'],
 ['subj_no'=>'ME 3B1', 'subj_name'=>'Methods of Research and Project Study 1'],
 ['subj_no'=>'ME 3B2', 'subj_name'=>'Refrigeration Systems'],
 ['subj_no'=>'ME 3B3', 'subj_name'=>'Fluids Machinery'],
 ['subj_no'=>'ME 3B4', 'subj_name'=>'Combustion Engineering'],
 ['subj_no'=>'ME 3B5', 'subj_name'=>'Materials Science & Engineering for ME'],
 ['subj_no'=>'ME 3B6', 'subj_name'=>'Mechanical Engineering Lab 1'],
 ['subj_no'=>'ME 3B7', 'subj_name'=>'Machine Design 1 (Lec)'],
 ['subj_no'=>'ME 3B8', 'subj_name'=>'Machine Design 1 (Lab)'],
 ['subj_no'=>'ME 2B1', 'subj_name'=>'Thermodynamics 2'],
 ['subj_no'=>'ME 2B2', 'subj_name'=>'Machine Elements'],
 ['subj_no'=>'Shop 2', 'subj_name'=>'Machine Shop Theory'],
 ['subj_no'=>'ECE 2B1', 'subj_name'=>'Electronics 2: Electronic Circuit Analysis and Design (Lec)'],
 ['subj_no'=>'ECE 2B2', 'subj_name'=>'Electronics 2: Electronic Circuit Analysis and Design (Lab)'],
 ['subj_no'=>'ECE 2B3', 'subj_name'=>'Communications 1: Principles of Communication Systems (Lec)'],
 ['subj_no'=>'ECE 2B4', 'subj_name'=>'Communications 1: Principles of Communication Systems (Lab)'],
 ['subj_no'=>'ECE 2B5', 'subj_name'=>'Advanced Engineering Mathematics (Lec)'],
 ['subj_no'=>'ECE 2B6', 'subj_name'=>'Advanced Engineering Mathematics (Lab)'],
 ['subj_no'=>'AC 2B1', 'subj_name'=>'Fundamentals of Electronic Circuits (Lec)'],
 ['subj_no'=>'AC 2B2', 'subj_name'=>'Fundamentals of Electronic Circuits (Lab)'],
 ['subj_no'=>'AC 2B1M', 'subj_name'=>'Basic Electronics (Lec)'],
 ['subj_no'=>'AC 2B2M', 'subj_name'=>'Basic Electronics (Lab)'],
 ['subj_no'=>'AC 201', 'subj_name'=>'Electronic Circuits: Devices and Analysis (Lec)'],
 ['subj_no'=>'AC 202', 'subj_name'=>'Electronic Circuits: Devices abd Analysis (Lab)'],
 ['subj_no'=>'AC 306', 'subj_name'=>'Microprocessor System'],
 ['subj_no'=>'ECE 3B1', 'subj_name'=>'Digital Electronics 2: Microprocessor & Microcontroller Systems and Design (Lec)'],
 ['subj_no'=>'ECE 3B2', 'subj_name'=>'Digital Electronics 2: Microprocessor & Microcontroller Systems and Design (Lab)'],
 ['subj_no'=>'ECE 3B3', 'subj_name'=>'Communications 3: Data Communications (Lec)'],
 ['subj_no'=>'ECE 3B4', 'subj_name'=>'Communications 3: Data Communications (Lab)'],
 ['subj_no'=>'ECE 3B5', 'subj_name'=>'Feedback and Control Systems (Lec)'],
 ['subj_no'=>'ECE 3B6', 'subj_name'=>'Feedback and Control Systems (Lab)'],
 ['subj_no'=>'ECE 3B7', 'subj_name'=>'Communication 4: Transmission Media Antenna System and Design (Lec)'],
 ['subj_no'=>'ECE 3B8', 'subj_name'=>'Communications 4: Transmission Media Antenna System and Design (Lab)'],
 ['subj_no'=>'ECE 3B9', 'subj_name'=>'ECE Laws Contracts Ethics Standards & Safety'],
 ['subj_no'=>'ECE EL 3A', 'subj_name'=>'Mechatronics'],
 ['subj_no'=>'ECE 4B1', 'subj_name'=>'Integrated Course 2 for ECE'],
 ['subj_no'=>'ECE 4B2', 'subj_name'=>'Design 2/Capstone Project 2'],
 ['subj_no'=>'ECE 4B3', 'subj_name'=>'Seminars/Colloquium'],
 ['subj_no'=>'ECE EL 2C1', 'subj_name'=>'ICT Infrastructure'],
 ['subj_no'=>'ECE EL 4E', 'subj_name'=>'Special Topics for ECE'],
 ['subj_no'=>'NS 1B3', 'subj_name'=>'Physics 2 (Lec)'],
 ['subj_no'=>'NS 1B4', 'subj_name'=>'Physics 2 (Lab)'],
 ['subj_no'=>'ES 2', 'subj_name'=>'Computer Aided Drafting'],
 ['subj_no'=>'CE 2B1', 'subj_name'=>'Highway and Railroad Engineering'],
 ['subj_no'=>'CE 4B2', 'subj_name'=>'CE Laws Ethics and Contracts'],
 ['subj_no'=>'CE 4B1', 'subj_name'=>'CE Project 2'],
 ['subj_no'=>'CE EL C7', 'subj_name'=>'Finite Element'],
 ['subj_no'=>'CE EL C6', 'subj_name'=>'Foundation and Retaining Wall Design'],
 ['subj_no'=>'CE 4B3', 'subj_name'=>'Integrated Course 2 for CE'],
 ['subj_no'=>'CE 4B4', 'subj_name'=>'Integrated Course 3 for CE'],
 ['subj_no'=>'ES 4', 'subj_name'=>'Dynamics of Rigid Bodies'],
 ['subj_no'=>'ES 10', 'subj_name'=>'Mechanics of Deformable Bodies'],
 ['subj_no'=>'CE 3B1', 'subj_name'=>'Quantity Surveying'],
 ['subj_no'=>'CE 3B2', 'subj_name'=>'Principles of Steel Design'],
 ['subj_no'=>'CE 3B3', 'subj_name'=>'Principles of Reinforced/Prestressed Concrete'],
 ['subj_no'=>'CE 3B4', 'subj_name'=>'Hydrology'],
 ['subj_no'=>'CE 3B5', 'subj_name'=>'Hydraulics'],
 ['subj_no'=>'CE 3B6', 'subj_name'=>'Geotechnical Engineering 1 (Soil Mechanics)'],
 ['subj_no'=>'CE 2S1', 'subj_name'=>'Geology for Civil Engineers'],
 ['subj_no'=>'EE 1B1', 'subj_name'=>'Electrical Engineering Technology'],
 ['subj_no'=>'EE 2B1', 'subj_name'=>'Electrical Circuits 2 (Lec)'],
 ['subj_no'=>'EE 2B2', 'subj_name'=>'Electrical Circuits 2 (Lab)'],
 ['subj_no'=>'EE 2B3', 'subj_name'=>'Electromagnetics'],
 ['subj_no'=>'EE 3B1', 'subj_name'=>'Electrical Apparatus and Devices (Lec)'],
 ['subj_no'=>'EE 3B2', 'subj_name'=>'Electrical Apparatus and Devices (Lab)'],
 ['subj_no'=>'EE 3B3', 'subj_name'=>'Electrical Engineering Safety'],
 ['subj_no'=>'EE 3B4', 'subj_name'=>'Electrical Standards and Practices'],
 ['subj_no'=>'EE 3B6', 'subj_name'=>'Feedback Control Systems'],
 ['subj_no'=>'EE 3B7', 'subj_name'=>'Research Methods'],
 ['subj_no'=>'EE 4B1', 'subj_name'=>'Distribution Systems and Substation Design (Lec)'],
 ['subj_no'=>'EE 4B2', 'subj_name'=>'Distribution Systems and Substation Design (Lab)'],
 ['subj_no'=>'EE 4B3', 'subj_name'=>'Fundamentals of Power Plant Engineering Design'],
 ['subj_no'=>'EE 4B4', 'subj_name'=>'Management of Engineering Projects'],
 ['subj_no'=>'EE 4B5', 'subj_name'=>'Seminars/Colloquia'],
 ['subj_no'=>'EE 4B6', 'subj_name'=>'EE Integrated Course 2'],
 ['subj_no'=>'EE EL 2', 'subj_name'=>'Electrical Engineering Elective 2'],
 ['subj_no'=>'EE EL 3', 'subj_name'=>'Electrical Engineering Elective 3'],
 ['subj_no'=>'EE EL 4', 'subj_name'=>'Electrical Engineering Elective 4'],
 ['subj_no'=>'ES 8', 'subj_name'=>'Engineering Mechanics'],
 ['subj_no'=>'AC 203', 'subj_name'=>'Basic Thermodynamics'],
 ['subj_no'=>'CE EL A3', 'subj_name'=>'Construction Cost Engineering'],
 ['subj_no'=>'CE EL A4', 'subj_name'=>'Database Management in Construction'],
 ['subj_no'=>'ES 5', 'subj_name'=>'Fundamentals of Deformable Bodies'],
 ['subj_no'=>'AC 307', 'subj_name'=>'Materials Science and Engineering'],
 ['subj_no'=>'AC 305', 'subj_name'=>'Fluid Mechanics'],
 ['subj_no'=>'CE 2S2', 'subj_name'=>'Construction Materials and Testing'],
 ['subj_no'=>'CE 3A1', 'subj_name'=>'Structural Theory'],
 ['subj_no'=>'PROF ED 02', 'subj_name'=>'Foundations of Special and Inclusive Education'],
 ['subj_no'=>'PROF ED 03', 'subj_name'=>'The Child and Adolescent Learner and Learning Principles'],
 ['subj_no'=>'ED-ELEM 03', 'subj_name'=>'Teaching Social Studies in Elementary Grades (Culture and Geography)'],
 ['subj_no'=>'ED-ELEM 04', 'subj_name'=>'Pagtuturo ng Filipino sa Elementarya II (Panitikan ng Pilipinas)'],
 ['subj_no'=>'ED-FIL MAJ 02', 'subj_name'=>'Estruktura ng Wikang Filipino'],
 ['subj_no'=>'ED-FIL MAJ 03', 'subj_name'=>'Barayti at Baryasyon ng Wika'],
 ['subj_no'=>'ED-ENG MAJ 03', 'subj_name'=>'Language Culture and Society'],
 ['subj_no'=>'ED-ENG MAJ 04', 'subj_name'=>'Principles and Theories of Language Acquisition and Learning'],
 ['subj_no'=>'ED-SCI 01', 'subj_name'=>'Astronomy'],
 ['subj_no'=>'ED-BIO 02', 'subj_name'=>'Genetics (Lec and Lab)'],
 ['subj_no'=>'ED-PED 03', 'subj_name'=>'Sports and Exercise Psychology'],
 ['subj_no'=>'ED-PED 04', 'subj_name'=>'Physiology of Exercise and Physical Activity'],
 ['subj_no'=>'ED-MATH MAJ 03', 'subj_name'=>'Trigonometry'],
 ['subj_no'=>'ED-MATH MAJ 04', 'subj_name'=>'Plane and Solid Geometry'],
 ['subj_no'=>'ED-ECED 03', 'subj_name'=>'Play and Developmentally Appropriate Practices in Early Childhood Education'],
 ['subj_no'=>'ED-ECED 04', 'subj_name'=>'Health Nutrition and Safety'],
 ['subj_no'=>'SNED 02', 'subj_name'=>'Learners with Sensory and Physical Disabilities'],
 ['subj_no'=>'PROF ED 06', 'subj_name'=>'The Teaching Profession'],
 ['subj_no'=>'PROF ED 07', 'subj_name'=>'Integrating Information and Communication Technology in 21st Century Learning Designs'],
 ['subj_no'=>'ED-ELEM 07', 'subj_name'=>'Teaching Physics Earth and Space Sciences in the Elementary Grades'],
 ['subj_no'=>'ED-ELEM 08', 'subj_name'=>'Teaching Math in the Intermediate Grades'],
 ['subj_no'=>'ED-ELEM 09', 'subj_name'=>'Language Arts Teaching in the Elementary Grades'],
 ['subj_no'=>'ED-ENG MAJ 08', 'subj_name'=>'Teaching and Assessment of Grammar'],
 ['subj_no'=>'ED-ENG MAJ 09', 'subj_name'=>'Survey of English and American Literature'],
 ['subj_no'=>'ED-ENG MAJ 10', 'subj_name'=>'Translation and Editing of Text'],
 ['subj_no'=>'ED-MATH MAJ 07', 'subj_name'=>'Calculus I with Analytic Geometry'],
 ['subj_no'=>'ED-MATH MAJ 08', 'subj_name'=>'Calculus II'],
 ['subj_no'=>'ED-MATH MAJ 09', 'subj_name'=>'Mathematics of Investment'],
 ['subj_no'=>'ED-CHEM 02', 'subj_name'=>'Organic Chemistry (Lec and Lab)'],
 ['subj_no'=>'ED-PHYSICS 02', 'subj_name'=>'Waves and Optics (Lec and Lab)'],
 ['subj_no'=>'SNED 05', 'subj_name'=>'Gifted and Talented Learners'],
 ['subj_no'=>'SNED 06', 'subj_name'=>'Adapted Physical Education and Recreation Music and Health'],
 ['subj_no'=>'ED-ECED 08', 'subj_name'=>'Numeracy Development'],
 ['subj_no'=>'ED-ECED 09', 'subj_name'=>'Literacy Development'],
 ['subj_no'=>'ED-PED 08', 'subj_name'=>'Personal Community and Environmental Health'],
 ['subj_no'=>'ED-PED 09', 'subj_name'=>'Philippine Traditional Dances'],
 ['subj_no'=>'ED-PED 10', 'subj_name'=>'Individual and Dual Sports (Racket Sports Athletics and Martial Arts)'],
 ['subj_no'=>'PROF ED 14', 'subj_name'=>'Assessment in Learning 2'],
 ['subj_no'=>'PROF ED 15', 'subj_name'=>'The Teacher and the School Curriculum'],
 ['subj_no'=>'PROF ED 16', 'subj_name'=>'Research 2 (Research in Education according to Area of Concentration)'],
 ['subj_no'=>'PROF ED 17', 'subj_name'=>'Field Study 1 (Observations of Teaching-Learning in Actual School Environment)'],
 ['subj_no'=>'ED-ENG MAJ 15', 'subj_name'=>'Literary Criticism'],
 ['subj_no'=>'ED-ENG MAJ 16', 'subj_name'=>'Stylistics and Discourse Analysis'],
 ['subj_no'=>'ED-ENG MAJ 17', 'subj_name'=>'Tchng. & Assessment of the Macro Skills (Expressive Skills-SpeakingWriting & Visually Representing)'],
 ['subj_no'=>'ED-ENG MAJ 18', 'subj_name'=>'Speech and Stage Arts'],
 ['subj_no'=>'ED-BIO 04', 'subj_name'=>'Zoology (Lec and Lab)'],
 ['subj_no'=>'ED-CHEM 04', 'subj_name'=>'Biochemistry'],
 ['subj_no'=>'ED-PHYSICS 04', 'subj_name'=>'Fluid Mechanics'],
 ['subj_no'=>'ED-SCI 02', 'subj_name'=>'Earth Science'],
 ['subj_no'=>'ED-ELEM 12', 'subj_name'=>'Teaching Music in the Elementary Grades'],
 ['subj_no'=>'ED-ELEM 13', 'subj_name'=>'Teaching Arts in the Elementary Grades'],
 ['subj_no'=>'ED-ELEM 14', 'subj_name'=>'Teaching PE and Health in the Elementary Grades'],
 ['subj_no'=>'SNED 10', 'subj_name'=>'Transition Education'],
 ['subj_no'=>'SNED 11', 'subj_name'=>'Educational Assessment of Students with Additional Needs'],
 ['subj_no'=>'ED-PED 14', 'subj_name'=>'Process of Teaching PE and Health Education'],
 ['subj_no'=>'ED-PED 15', 'subj_name'=>'Applied Motor Control and Learning of Exercise Sports and Dance'],
 ['subj_no'=>'ED-PED 16', 'subj_name'=>'Drugs Education Consumer Health and Nutrition'],
 ['subj_no'=>'ED-ECED 14', 'subj_name'=>'Infant and Toddlers Programs'],
 ['subj_no'=>'ED-ECED 15', 'subj_name'=>'Early Childhood Education Curriculum Models'],
 ['subj_no'=>'ED-ECED 16', 'subj_name'=>'Family School and Community Partnerships'],
 ['subj_no'=>'ED-MATH MAJ 13', 'subj_name'=>'Advanced Statistics'],
 ['subj_no'=>'ED-MATH MAJ 14', 'subj_name'=>'Number Theory'],
 ['subj_no'=>'ED-FIL MAJ 15', 'subj_name'=>'Introduksyon sa Pagsasalin'],
 ['subj_no'=>'ED-FIL MAJ 16', 'subj_name'=>'Maikling Kwento at Nobelang Filipino'],
 ['subj_no'=>'ED-FIL MAJ 17', 'subj_name'=>'Dulaang Filipino'],
 ['subj_no'=>'PROF ED 20', 'subj_name'=>'Practice Teaching/Teaching Internship'],
 ['subj_no'=>'PROF ED 21', 'subj_name'=>'Special Topics in Education'],
 ['subj_no'=>'Ed-TP', 'subj_name'=>'Teaching Profession'],
 ['subj_no'=>'Ed-FL', 'subj_name'=>'Facilitating Learning'],
 ['subj_no'=>'Ed-PT 1', 'subj_name'=>'Principles of Teaching 1'],
 ['subj_no'=>'Ed-Asl 1', 'subj_name'=>'Assessment of Student Learning 1'],
 ['subj_no'=>'Ed-Tech 1', 'subj_name'=>'Principles and Theories of Educational Technology'],
 ['subj_no'=>'D-Rdg 1', 'subj_name'=>'Developmental Reading 1'],
 ['subj_no'=>'Ed FS A', 'subj_name'=>'Field Study 12 & 3'],
 ['subj_no'=>'Ed-CD', 'subj_name'=>'Curriculum Development'],
 ['subj_no'=>'Ed-Pract', 'subj_name'=>'Practice Teaching'],
 ['subj_no'=>'Ed FS B', 'subj_name'=>'Field Study 45 & 6'],
 ['subj_no'=>'PE 2', 'subj_name'=>'Physical Education 2'],
 ['subj_no'=>'PE 4', 'subj_name'=>'Physical Education 4'],
 ['subj_no'=>'GE UTS', 'subj_name'=>'Understanding the Self'],
 ['subj_no'=>'GE MMW', 'subj_name'=>'Mathematics in the Modern World'],
 ['subj_no'=>'GE STS', 'subj_name'=>'Science Technology and Society'],
 ['subj_no'=>'GE AA', 'subj_name'=>'Art Appreciation'],
 ['subj_no'=>'Psych 3', 'subj_name'=>'Social Psychology'],
 ['subj_no'=>'Psych 4A', 'subj_name'=>'Theories of Personality 1'],
 ['subj_no'=>'Psych 5', 'subj_name'=>'Cognitive Psychology'],
 ['subj_no'=>'Psych 6', 'subj_name'=>'Filipino Psychology'],
 ['subj_no'=>'Psych 9', 'subj_name'=>'Experimental Psychology'],
 ['subj_no'=>'Psych 10A', 'subj_name'=>'Counseling and Psychotheraphy 1'],
 ['subj_no'=>'Psych 11A', 'subj_name'=>'Abnormal Psychology 1'],
 ['subj_no'=>'Psych 12', 'subj_name'=>'Field Methods in Psychology'],
 ['subj_no'=>'Psych 15B', 'subj_name'=>'Psychological Assessment 2'],
 ['subj_no'=>'Psych 16A', 'subj_name'=>'Research in Psychology 1'],
 ['subj_no'=>'Psych 17', 'subj_name'=>'Seminar on Current Issues in Psychology'],
 ['subj_no'=>'Psych 29', 'subj_name'=>'Psychology of Technology'],
 ['subj_no'=>'Psych 25', 'subj_name'=>'Integrated Course on Personality'],
 ['subj_no'=>'Psych 26', 'subj_name'=>'Integrated Course on Abnormal Psychology'],
 ['subj_no'=>'Psych 27', 'subj_name'=>'Integrated Course on Psychological Assessment'],
 ['subj_no'=>'Psych 28', 'subj_name'=>'Integrated Course on Industrial Psychology'],
 ['subj_no'=>'CHEM 102', 'subj_name'=>'Organic Chemistry'],
 ['subj_no'=>'Lab Sci 2', 'subj_name'=>'Human Anatomy and Physiology'],
 ['subj_no'=>'Psych Math C', 'subj_name'=>'Computer Aided Statistical Analysis for Behavioral Science'],
 ['subj_no'=>'EP 1', 'subj_name'=>'English Proficiency Level 1 (lec/lab)'],
 ['subj_no'=>'EfCom', 'subj_name'=>'Effective Communication'],
 ['subj_no'=>'GE PC', 'subj_name'=>'Purposive Communication'],
 ['subj_no'=>'Lit 1', 'subj_name'=>'The Literatures of the Philippines'],
 ['subj_no'=>'Lit 2', 'subj_name'=>'The Literatures of the World'],
 ['subj_no'=>'Engl Seminar', 'subj_name'=>'Seminar on English Language Literature and other Related Thrusts'],
 ['subj_no'=>'KOMFIL', 'subj_name'=>'Kontekstwalisadong Komunikasyon sa Filipino'],
 ['subj_no'=>'FILDIS', 'subj_name'=>'Filipino sa Ibat-ibang Disiplina'],
 ['subj_no'=>'F-LANG F1', 'subj_name'=>'French 1'],
 ['subj_no'=>'ADV CMP', 'subj_name'=>'Calculus'],
 ['subj_no'=>'GE ET', 'subj_name'=>'Ethics'],
 ['subj_no'=>'Rizal', 'subj_name'=>'Life and Works of Dr. Jose Rizal'],
 ['subj_no'=>'GE RPH', 'subj_name'=>'Readings in Philippine History'],
 ['subj_no'=>'GE TCW', 'subj_name'=>'The Contemporary World'],
 ['subj_no'=>'Econ 2', 'subj_name'=>'Basic Microeconomics'],
 ['subj_no'=>'Pol. Sci. Major 2', 'subj_name'=>'Introduction to Philippine Politics and Governance'],
 ['subj_no'=>'Pol. Sci. Major 4', 'subj_name'=>'Introduction to Political Theory including Ancient and Medieval Political Theory'],
 ['subj_no'=>'Pol. Sci. Major 5A', 'subj_name'=>'Qualitative Analysis of Political Data'],
 ['subj_no'=>'Pol. Sci. Elec 3', 'subj_name'=>'Political Parties and Interest Groups'],
 ['subj_no'=>'Pol. Sci. Elec 4', 'subj_name'=>'Modern and Contemporary Political Theories'],
 ['subj_no'=>'Pol. Sci. Major 5B', 'subj_name'=>'Quantitative Analysis of Political Data'],
 ['subj_no'=>'Pol. Sci. Major 8', 'subj_name'=>'Introduction to International Relations'],
 ['subj_no'=>'Pol. Sci. Major 9', 'subj_name'=>'Politics and Governance in Southeast Asia'],
 ['subj_no'=>'Free Elec 3', 'subj_name'=>'Politics and Governance in East Asia'],
 ['subj_no'=>'Free Elec 4', 'subj_name'=>'Political Economy'],
 ['subj_no'=>'Interdisciplina El 1', 'subj_name'=>'Taxation Laws'],
 ['subj_no'=>'Interdisciplina El 2', 'subj_name'=>'Philippine Legal Forms'],
 ['subj_no'=>'Pol. Sci. Elec 7', 'subj_name'=>'Obligations and Contracts'],
 ['subj_no'=>'Pol. Sci. Elec 8', 'subj_name'=>'Introduction to Criminal Law'],
 ['subj_no'=>'Pol. Sci. Elec 9', 'subj_name'=>'Philippine Labor Law'],
 ['subj_no'=>'Pol. Sci. Elec 10', 'subj_name'=>'Election Laws/Omnibus Election Code'],
 ['subj_no'=>'IS 2', 'subj_name'=>'Philippine Foreign Relations'],
 ['subj_no'=>'IS 3', 'subj_name'=>'World History'],
 ['subj_no'=>'IS 5', 'subj_name'=>'Theories of International Relations'],
 ['subj_no'=>'IS 6', 'subj_name'=>'International Law'],
 ['subj_no'=>'IS 7', 'subj_name'=>'Area Studies 2: Southeast Asian Studies'],
 ['subj_no'=>'Research 2', 'subj_name'=>'Quantitative Methods in the Social Sciences'],
 ['subj_no'=>'IS 11', 'subj_name'=>'Issues in Developing Nations'],
 ['subj_no'=>'IS 12', 'subj_name'=>'Area Studies 4: American Studies'],
 ['subj_no'=>'IS Elec 2', 'subj_name'=>'PERD: Diplomatic Dinner'],
 ['subj_no'=>'IS 16', 'subj_name'=>'Conflict Resolution and Management'],
 ['subj_no'=>'IS 17', 'subj_name'=>'Area Studies 6: Middle East and North African Studies'],
 ['subj_no'=>'IS Elec 3', 'subj_name'=>'Bill of Rights Citizenship and Society'],
 ['subj_no'=>'Free Elec', 'subj_name'=>'Integrated Course for IS'],
 ['subj_no'=>'Philo Maj. 2', 'subj_name'=>'Logic with Argumentation and Debate'],
 ['subj_no'=>'Philo Maj. 3', 'subj_name'=>'History of Western Philosophy 1'],
 ['subj_no'=>'Philo Maj. 4', 'subj_name'=>'History of Chinese Philosophy'],
 ['subj_no'=>'Philo Maj. 8', 'subj_name'=>'History of Indian Philosophy'],
 ['subj_no'=>'Philo Maj. 9', 'subj_name'=>'Postmodernism'],
 ['subj_no'=>'Philo Maj. 10', 'subj_name'=>'Aesthetics/Theories of Art'],
 ['subj_no'=>'Philo Maj. 11', 'subj_name'=>'Epistemology'],
 ['subj_no'=>'English 20', 'subj_name'=>'Advanced Grammar & Composition'],
 ['subj_no'=>'English 7', 'subj_name'=>'Business English Correspondence'],
 ['subj_no'=>'French 2', 'subj_name'=>'Conversational French'],
 ['subj_no'=>'F-LANG 3', 'subj_name'=>'Chinese/Japanese/French/Spanish'],
 ['subj_no'=>'ELS 100', 'subj_name'=>'Introduction to the English Language System'],
 ['subj_no'=>'ELS 102', 'subj_name'=>'Theories of Language and Language Acquisition'],
 ['subj_no'=>'ELS 106', 'subj_name'=>'Semantics of English'],
 ['subj_no'=>'ELS 109', 'subj_name'=>'Introduction to Language Society and Culture'],
 ['subj_no'=>'ELS 110', 'subj_name'=>'Language of Literary Texts'],
 ['subj_no'=>'ELS 127', 'subj_name'=>'Introduction to Anthropological Lingusitics'],
 ['subj_no'=>'ELS 143', 'subj_name'=>'Language and Advertising'],
 ['subj_no'=>'ELS 200', 'subj_name'=>'Language Research 2: Thesis'],
 ['subj_no'=>'ELS 126', 'subj_name'=>'Translation Studies'],
 ['subj_no'=>'ELS 144', 'subj_name'=>'Language and Media/Cebuano Media Writing'],
 ['subj_no'=>'ELS 128', 'subj_name'=>'Philippine English'],
 ['subj_no'=>'ELS 129', 'subj_name'=>'Issues and Perspective in English Language Studies'],
 ['subj_no'=>'ELS 147', 'subj_name'=>'Organizational Communication'],
 ['subj_no'=>'Stat 1', 'subj_name'=>'Fundamentals of Statistics'],
 ['subj_no'=>'Internship', 'subj_name'=>'Practicum/Internship (600 hours)'],
 ['subj_no'=>'Thesis 1', 'subj_name'=>'Thesis 1'],
 ['subj_no'=>'Com 21', 'subj_name'=>'Knowledge Management'],
 ['subj_no'=>'Com 24', 'subj_name'=>'Television Production and Programming (Lec/Lab)'],
 ['subj_no'=>'Society 4', 'subj_name'=>'State of Philippine Education with College Teaching'],
 ['subj_no'=>'Com 23', 'subj_name'=>'Communication Management'],
 ['subj_no'=>'Com 22', 'subj_name'=>'Development Communication'],
 ['subj_no'=>'Com 8', 'subj_name'=>'Broadcasting Principles and Practices'],
 ['subj_no'=>'Com 13', 'subj_name'=>'Cebuano Media Writing'],
 ['subj_no'=>'Society 2', 'subj_name'=>'Social and Cultural Perspective of Development (Lec/Lab)'],
 ['subj_no'=>'Com 15', 'subj_name'=>'Public Relations Principles and Practices'],
 ['subj_no'=>'Com Elec 1', 'subj_name'=>'Multimedia Storytelling/Reporting (Lec/Lab)'],
 ['subj_no'=>'Com 10', 'subj_name'=>'Photography (Lec/Lab)'],
 ['subj_no'=>'Com 2', 'subj_name'=>'Communication Theory'],
 ['subj_no'=>'Com 3', 'subj_name'=>'Communication Culture and Society'],
 ['subj_no'=>'SocSci 2', 'subj_name'=>'Social and Cultural Perspective of Development'],
 ['subj_no'=>'Com Elec A', 'subj_name'=>'Theater Arts: Appreciation and Production'],
 ['subj_no'=>'Advert 8', 'subj_name'=>'Digital Layouting for Visual Collaterals (Lec/Lab)'],
 ['subj_no'=>'Advert 9', 'subj_name'=>'Marketing Proposals and Collaterals'],
 ['subj_no'=>'Mktg 8', 'subj_name'=>'Principles of Economics and Taxation'],
 ['subj_no'=>'Advert 3', 'subj_name'=>'Advertising Photography (Lec/Lab)'],
 ['subj_no'=>'Advert 4', 'subj_name'=>'Visual Literacy Aesthetic and Design'],
 ['subj_no'=>'Com Maj 2', 'subj_name'=>'Communiation Theories'],
 ['subj_no'=>'Com Maj 3', 'subj_name'=>'Communication Media Culture and Society'],
 ['subj_no'=>'Journ 22', 'subj_name'=>'Editorial Management'],
 ['subj_no'=>'Journ 23', 'subj_name'=>'News Editing and Production-Purveyor (Lec/Lab)'],
 ['subj_no'=>'Journ 27', 'subj_name'=>'Television Broadcast Production and Programming - News Set (Lec/Lab)'],
 ['subj_no'=>'Journ Elec 4', 'subj_name'=>'Community Journalism'],
 ['subj_no'=>'Econ A', 'subj_name'=>'Applied Economics'],
 ['subj_no'=>'EP 2', 'subj_name'=>'English Proficiency Level 2'],
 ['subj_no'=>'LIS 102', 'subj_name'=>'Collection Management of Information Resources'],
 ['subj_no'=>'ICT 102', 'subj_name'=>'Web Technologies in Libraries and Information Centers'],
 ['subj_no'=>'LIS 105', 'subj_name'=>'Information Resources and Services 2'],
 ['subj_no'=>'LIS 106', 'subj_name'=>'Organization of Information Resources 2'],
 ['subj_no'=>'LIS 107', 'subj_name'=>'Indexing and Abstracting'],
 ['subj_no'=>'ICT 104', 'subj_name'=>'Programming Fundamentals'],
 ['subj_no'=>'SpT 105', 'subj_name'=>'Preservation of Information Resources'],
 ['subj_no'=>'SpT 106', 'subj_name'=>'Foreign Language 1 (Elective)'],
 ['subj_no'=>'SpT 107', 'subj_name'=>'Indigenous Knowledge and Multi-Culturalism'],
 ['subj_no'=>'LIS 110', 'subj_name'=>'Thesis 1: Research Methods in Library and Information Science 1'],
 ['subj_no'=>'LIS 111', 'subj_name'=>'Library Materials for Children and Young Adults'],
 ['subj_no'=>'LIS 113', 'subj_name'=>'Introduction to Records Management and Archives'],
 ['subj_no'=>'LPr 02', 'subj_name'=>'Library Practice: Practicum 2 (200 hours)'],
 ['subj_no'=>'Integrated Course A', 'subj_name'=>'Integrated Course on Indexing & Abstracting Cataloging & Classification and Reference'],
 ['subj_no'=>'Integrated Course B', 'subj_name'=>'Integrated Course on Information Technology Collection Management and Library Management'],
 ['subj_no'=>'Society 1', 'subj_name'=>'Philippine Government and Politics'],
 ['subj_no'=>'Research 1', 'subj_name'=>'Thesis 1'],
 ['subj_no'=>'Bio-FC 3', 'subj_name'=>'Principles of Taxonomy and Systematics Lecture'],
 ['subj_no'=>'Bio-FC 3L', 'subj_name'=>'Principles of Taxonomy and Systematics Laboratory'],
 ['subj_no'=>'Bio-FC 4', 'subj_name'=>'General Ecology Lecture'],
 ['subj_no'=>'Bio-FC 4L', 'subj_name'=>'General Ecology Laboratory'],
 ['subj_no'=>'Chem-Bio 1', 'subj_name'=>'Organic Molecules Lecture'],
 ['subj_no'=>'Chem-Bio 1L', 'subj_name'=>'Organic Molecules Laboratory'],
 ['subj_no'=>'Chem-Bio 3', 'subj_name'=>'Biochemistry (Biomolecules) Lecture'],
 ['subj_no'=>'Chem-Bio 3L', 'subj_name'=>'Biochemistry (Biomolecules) Laboratory'],
 ['subj_no'=>'Bio-FC 5', 'subj_name'=>'General Physiology Lecture'],
 ['subj_no'=>'Bio-FC 5L', 'subj_name'=>'General Physiology Laboratory'],
 ['subj_no'=>'Bio-FC 9', 'subj_name'=>'Principles of Genetics Lecture'],
 ['subj_no'=>'Bio-FC 9L', 'subj_name'=>'Principles of Genetics Laboratory'],
 ['subj_no'=>'Bio-FC 10', 'subj_name'=>'Evolutionary Biology Lecture'],
 ['subj_no'=>'Bio-FC 10L', 'subj_name'=>'Evolutionary Biology Laboratory'],
 ['subj_no'=>'Bio-Med 1', 'subj_name'=>'Human Anatomy and Physiology Lecture'],
 ['subj_no'=>'Bio-Med 1L', 'subj_name'=>'Human Anatomy and Physiology Laboratory'],
 ['subj_no'=>'Bio-Health 1', 'subj_name'=>'Health Care and Life Support'],
 ['subj_no'=>'Bio-Micro 1', 'subj_name'=>'Microbial Taxonomy Lecture'],
 ['subj_no'=>'Bio-Micro 1L', 'subj_name'=>'Microbial Taxonomy Laboratory'],
 ['subj_no'=>'Bio-Med 5', 'subj_name'=>'Medical Human Genetics Lecture'],
 ['subj_no'=>'Bio-Med 5L', 'subj_name'=>'Medical Human Genetics Laboratory'],
 ['subj_no'=>'Bio-Med 6', 'subj_name'=>'Medical Microbiology Lecture'],
 ['subj_no'=>'Bio-Med 6L', 'subj_name'=>'Medical Microbiology Laboratory'],
 ['subj_no'=>'Bio-Med 7', 'subj_name'=>'General Pathology and Epidemiology Lecture'],
 ['subj_no'=>'Bio-Med 7L', 'subj_name'=>'General Pathology and Epidemiology Laboratory'],
 ['subj_no'=>'Bio-Res 2', 'subj_name'=>'Research 2 Final Paper and Publication'],
 ['subj_no'=>'Bio-Micro 5', 'subj_name'=>'Food Microbiology Lecture'],
 ['subj_no'=>'Bio-Micro 5L', 'subj_name'=>'Food Microbiology Laboratory'],
 ['subj_no'=>'Bio-Micro 6', 'subj_name'=>'Industrial Microbiology Lecture'],
 ['subj_no'=>'Bio-Micro 6L', 'subj_name'=>'Industrial Microbiology Laboratory'],
 ['subj_no'=>'Bio-Micro 7', 'subj_name'=>'General Pathology and Epidemiology Lecture'],
 ['subj_no'=>'Bio-Micro 7L', 'subj_name'=>'General Pathology and Epidemiology Laboratory'],
 ['subj_no'=>'Stat', 'subj_name'=>'Statistical Analysis with Software Application'],
 ['subj_no'=>'ELS 123', 'subj_name'=>'Language of Law'],
 ['subj_no'=>'ELS 124', 'subj_name'=>'Organizational Communication'],
 ['subj_no'=>'ELS 117', 'subj_name'=>'Language Research 1: Methodology'],
 ['subj_no'=>'ELS 118', 'subj_name'=>'Language and Gender'],
 ['subj_no'=>'ELS 120', 'subj_name'=>'Language of the Internet'],
 ['subj_no'=>'Llb 121', 'subj_name'=>'Obligation & Contracts'],
 ['subj_no'=>'Llb 122', 'subj_name'=>'Constitutional II'],
 ['subj_no'=>'Llb 123', 'subj_name'=>'Criminal Law II'],
 ['subj_no'=>'Llb 124', 'subj_name'=>'Legal Technique and Logic'],
 ['subj_no'=>'Llb 125', 'subj_name'=>'Basic Legal Ethics'],
 ['subj_no'=>'Llb 126', 'subj_name'=>'Special Penal Laws'],
 ['subj_no'=>'Llb 221', 'subj_name'=>'Civil Procedure'],
 ['subj_no'=>'Llb 222', 'subj_name'=>'Negotiable Instruments'],
 ['subj_no'=>'Llb 223', 'subj_name'=>'Credit Transactions'],
 ['subj_no'=>'Llb 224', 'subj_name'=>'Labor Law II'],
 ['subj_no'=>'LlB 225', 'subj_name'=>'Administrative Law Law on Public Officers & Election Law'],
 ['subj_no'=>'Llb 226', 'subj_name'=>'Public International Law'],
 ['subj_no'=>'Llb 227', 'subj_name'=>'Alternative Dispute Resolution'],
 ['subj_no'=>'LLB 321', 'subj_name'=>'Evidence'],
 ['subj_no'=>'LLB 322', 'subj_name'=>'Corporation Law'],
 ['subj_no'=>'LLB 323', 'subj_name'=>'Taxation II'],
 ['subj_no'=>'Llb 324', 'subj_name'=>'Special Proceedings'],
 ['subj_no'=>'LLB 325', 'subj_name'=>'Torts and Damages'],
 ['subj_no'=>'Llb 326', 'subj_name'=>'Legal Forms'],
 ['subj_no'=>'LLB 327', 'subj_name'=>'Problem Areas in Legal Ethics'],
 ['subj_no'=>'LLB 328', 'subj_name'=>'Special Commercial Laws'],
 ['subj_no'=>'LLB 421', 'subj_name'=>'Remedial Law Review II'],
 ['subj_no'=>'LLB 422', 'subj_name'=>'Civil Law Review II'],
 ['subj_no'=>'Llb 423', 'subj_name'=>'Commercial Law Review'],
 ['subj_no'=>'LLB 424', 'subj_name'=>'Legal Counseling and Social Responsibility'],
 ['subj_no'=>'LLB 425', 'subj_name'=>'Practice Court II'],
 ['subj_no'=>'LLB 426', 'subj_name'=>'Taxation Law Review'],
 ['subj_no'=>'LLB 427', 'subj_name'=>'Elective (Seminar)'],
 ['subj_no'=>'SEMTOUR', 'subj_name'=>'Seminars and Tours'],
 ['subj_no'=>'Digital', 'subj_name'=>'Digital Logic Design'],
 ['subj_no'=>'Prog 2', 'subj_name'=>'Computer Programming 2'],
 ['subj_no'=>'Prac', 'subj_name'=>'Practicum (486 hours)'],
 ['subj_no'=>'Discrete 1', 'subj_name'=>'Discrete Structures 1'],
 ['subj_no'=>'FIT', 'subj_name'=>'Foundation in Information Technology (Lec/Lab)'],
 ['subj_no'=>'IM 1', 'subj_name'=>'Information Management'],
 ['subj_no'=>'Net 1', 'subj_name'=>'Data Communications and Networking 1'],
 ['subj_no'=>'Algo', 'subj_name'=>'Analysis and Design of Algorithms'],
 ['subj_no'=>'OOP', 'subj_name'=>'Object Oriented Programming'],
 ['subj_no'=>'DVA', 'subj_name'=>'Digital Visual Arts'],
 ['subj_no'=>'IM 3', 'subj_name'=>'Fundamentals of Data Analytics'],
 ['subj_no'=>'IAS 2', 'subj_name'=>'Information Assurance and Security 2'],
 ['subj_no'=>'IPT', 'subj_name'=>'Integrative Programming and Technologies'],
 ['subj_no'=>'SIA', 'subj_name'=>'System Integration and Architecture'],
 ['subj_no'=>'Research', 'subj_name'=>'Methods of Research in Computing'],
 ['subj_no'=>'Prof Elec 2', 'subj_name'=>'Professional Elective 2'],
 ['subj_no'=>'SP Elec 2A', 'subj_name'=>'Web Application Development 2'],
 ['subj_no'=>'SP Elec 2B', 'subj_name'=>'Mobile Application Development 2'],
 ['subj_no'=>'SP Elec 2C', 'subj_name'=>'Multimedia Application Development 2'],
 ['subj_no'=>'EMC CORE 2', 'subj_name'=>'Introduction to Game Design and Development'],
 ['subj_no'=>'EMC CORE 5', 'subj_name'=>'Computer Graphics Programming'],
 ['subj_no'=>'EMC SP 2', 'subj_name'=>'Applied Game Physics'],
 ['subj_no'=>'PL', 'subj_name'=>'Programming Languages'],
 ['subj_no'=>'CS Elective 2', 'subj_name'=>'Graphics and Visual Computing'],
 ['subj_no'=>'CS Elective 3', 'subj_name'=>'Natural Language Processing'],
 ['subj_no'=>'Apps Dev 2', 'subj_name'=>'Applications Development and Emerging Technologies 2'],
 ['subj_no'=>'Free Elec 1', 'subj_name'=>'Free Elective 1'],
 ['subj_no'=>'IS', 'subj_name'=>'Fundamentals of Information Systems'],
 ['subj_no'=>'Capstone 1', 'subj_name'=>'Capstone Project 1'],
 ['subj_no'=>'Capstone 2', 'subj_name'=>'Capstone Project 2'],
 ['subj_no'=>'DM 4', 'subj_name'=>'Evaluation of Business Performance'],
 ['subj_no'=>'ReEd 2', 'subj_name'=>'Written That You May Believe: An Introduction to Biblical Exegesis'],
 ['subj_no'=>'ReEd 4', 'subj_name'=>'A Call to Action: An Introduction to Catholic Social Thought'],
 ['subj_no'=>'ReEd 1', 'subj_name'=>'Initium Fidei: An Introduction to Doing Catholic Theology'],
 ['subj_no'=>'ReEd 3', 'subj_name'=>'Our Restless Hearts: An Introduction to Doing Catholic Morality'],
 ['subj_no'=>'CWTS 12*', 'subj_name'=>'Civic Welfare Training Services 12'],
 ['subj_no'=>'NCM 101', 'subj_name'=>'Health Assessment'],
 ['subj_no'=>'NCM 101 (RLE)', 'subj_name'=>'Health Assessment'],
 ['subj_no'=>'NCM 102', 'subj_name'=>'Health Education'],
 ['subj_no'=>'NCM 103', 'subj_name'=>'Fundamentals of Nursing Practices'],
 ['subj_no'=>'NCM 103 (RLE)', 'subj_name'=>'Fundamentals of Nursing Practice'],
 ['subj_no'=>'MC 3', 'subj_name'=>'Microbiology and Parasitology (Lec)'],
 ['subj_no'=>'NCM 109', 'subj_name'=>'Care of Mother Child at Risk or with Problems (Acute and Chronic)'],
 ['subj_no'=>'NCM 109 (RLE)', 'subj_name'=>'Care of Mother Child at Risk or Problems (Acute and Chronic)'],
 ['subj_no'=>'NCM 110', 'subj_name'=>'Nursing Informatics'],
 ['subj_no'=>'NCM 110 (Lab)', 'subj_name'=>'Nursing Informatics'],
 ['subj_no'=>'NCM 115', 'subj_name'=>'Nursing Research 2'],
 ['subj_no'=>'NCM 116', 'subj_name'=>'Care of Clients with Problems in Nutrition and Gastro-intestinal Metabolism and Endocrine Percepti'],
 ['subj_no'=>'NCM 116 (RLE)', 'subj_name'=>'Care of Clients with Problems in Nutrition and Gastrointestinal Metabolism and Endocrine'],
 ['subj_no'=>'NCM 117', 'subj_name'=>'Care of Clients with Maladaptive Patterns of Behavior Acute and Chronic'],
 ['subj_no'=>'NCM 117 (RLE)', 'subj_name'=>'Care of Clients with Maladaptive Patterns of Behavior Acute and Chronic'],
 ['subj_no'=>'NCM 120', 'subj_name'=>'Disaster Nursing'],
 ['subj_no'=>'NCM 120 (RLE)', 'subj_name'=>'Disaster Nursing'],
 ['subj_no'=>'NCM 121 (RLE)', 'subj_name'=>'Intensive Nursing Practicum (Hospital and Community Settings)'],
 ['subj_no'=>'NU 2', 'subj_name'=>'Nursing Updates 2'],
 ['subj_no'=>'MLS 103B', 'subj_name'=>'Health Information System II (Medical Transcription II)'],
 ['subj_no'=>'MLS 104', 'subj_name'=>'Principles of Medical Laboratory Science Practice 2'],
 ['subj_no'=>'CHEM 103A', 'subj_name'=>'Qualitative Chemistry'],
 ['subj_no'=>'HUMHIS', 'subj_name'=>'Human Histology'],
 ['subj_no'=>'CLIBAC', 'subj_name'=>'Clinical Bacteriology'],
 ['subj_no'=>'CYTGEN', 'subj_name'=>'Cytogenetics'],
 ['subj_no'=>'METHIC', 'subj_name'=>'Med Tech Laws and Bioethics'],
 ['subj_no'=>'Guidance 2', 'subj_name'=>'Adjustment to College Life Phase 2'],
 ];

 DB::table('subject')->insert($data);
}

}
